tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "ack"
brew "cloc"
brew "elixir"
brew "fd"
brew "fzf"
brew "gh"
brew "gnu-sed"
brew "gnupg"
brew "macvim"
brew "ruby-build"
brew "rbenv"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "the_silver_searcher"
brew "tmux"
brew "tree"
brew "zsh"

cask "android-file-transfer"
cask "bluesnooze"
cask "middleclick"
cask "monitorcontrol"
cask "rectangle"
cask "skitch"
cask "vlc"

# personal only
#tap "superfly/tap"
#brew "superfly/tap/flyctl"
#cask "qbittorrent"
